# this file we need to keep outside scraper folder. Here we configure our database details

HOST: 127.0.0.1:3307
#DB_NAME: gts
DB_NAME: gts
DB_USERNAME: gtsadmin
DB_PASSWORD: gtsadmin


#engine = create_engine('mysql+mysqldb://' + DB_USERNAME + ':' + DB_PASSWORD + '@' + HOST + '/' +DB_NAME)
#engine = create_engine('mysql+mysqldb://root:vidyayug2022@127.0.0.1:3306/gts_local')